// Generated by CoffeeScript 1.9.1
(function() {
  var render;

  describe("TEST D3line class", function() {
    describe('set data', function() {
      beforeEach(function() {
        render();
        this.visualisation = document.querySelector('.d3linesvg');
        return this.d3line = new D3Line(this.visualisation);
      });
      return it("width is set with right data", function() {
        var result;
        result = this.d3line.width;
        return assert(result === 500 * 0.8);
      });
    });
    return describe('call function', function() {
      beforeEach(function() {
        render();
        return this.visualisation = document.querySelector('.d3linesvg');
      });
      return it('draw called once', function() {
        var d3line, mock, result;
        d3line = new D3Line(this.visualisation);
        mock = sinon.mock(d3line);
        mock.expects("drawline").once().returns(3);
        result = d3line.draw();
        console.log(result);
        mock.verify();
        return mock.restore();
      });
    });
  });

  render = function() {
    var svg;
    return svg = d3.select('body').append('svg').attr('class', 'd3linesvg').attr('height', '500').attr('width', '500');
  };

}).call(this);

//# sourceMappingURL=testd3lineclass.js.map
