// Generated by CoffeeScript 1.9.1
(function() {
  this.barChart = (function() {
    function barChart() {}

    barChart.prototype.setData = function(d) {
      this.data = d;
      this.h = 500 - 80;
      return this.w = 500;
    };

    barChart.prototype.getData = function() {
      return this.data;
    };

    barChart.prototype.render = function() {
      var _this, bars, svg, x, y;
      _this = this;
      if (this.data === void 0) {
        this.data = [];
      }
      svg = d3.select('body').append('svg').attr('height', '500').attr('width', '500').append('g').attr("transform", "translate('0, 0')");
      x = d3.scale.ordinal().rangeRoundBands([0, this.w], .05);
      x.domain(this.data.map(function(d) {
        return d.date;
      }));
      y = d3.scale.linear().range([this.h, 0]);
      y.domain([
        0, d3.max(this.data, function(d) {
          return d.value;
        })
      ]);
      bars = svg.selectAll('.bar').data(this.getData());
      return bars.enter().append('rect').attr('class', 'bar').attr('x', function(d) {
        return x(d.date);
      }).attr('width', x.rangeBand()).attr('y', function(d) {
        return y(d.value);
      }).attr('height', function(d) {
        return _this.h - y(d.value);
      });
    };

    return barChart;

  })();

}).call(this);

//# sourceMappingURL=barchart.js.map
