// Generated by CoffeeScript 1.9.1
(function() {
  this.D3Line = (function() {
    function D3Line(visualisation) {
      this.visualisation = visualisation;
      this.widths = this.visualisation.clientWidth * 0.8;
    }

    D3Line.prototype.draw = function() {
      return 1;
    };

    return D3Line;

  })();

}).call(this);

//# sourceMappingURL=d3line.js.map
